prompt: |
  I need your help to output a .csv file containing new {language} sentences based on a student's existing vocabulary.
  Your output must be only a .csv file, with no other content.
  Imagine you are a {language} teacher, helping a native English speaker who has just started learning {language}.
  So far the student has learned the following words, which we can call the 'learned words', and are as follows:
  {learned_tokens}

  Today the student is trying to learn the following words, which we can call the 'new words', and are as follows:
  {new_tokens}

  Based on the above information, please generate {n_sentences} new {language} sentences and return them as a .csv file with a column titled 'sentence'. Each sentence must meet all of the following criteria:
  - Each sentence includes _exactly one_ of the 'new words' -- you are NOT ALLOWED to include more than one word from the list of 'new words';
  - All of the other words in each sentence (besides the exactly one 'new word') must already appear in the list of 'learned words';
  - Each sentence must include a subject, a verb, and an object.
  Please use correct grammar and formal sentence structure when writing the sentences.
  Include as many of the words from the list of 'learned words' as you can in each sentence while still respecting the rules I mentioned above.
  Try to include a different 'new word' in each sentence.
  {grammar_instruction}
  The output format of the new sentences you generate should be a .csv with a column for the {language} sentence,
  a column for the English translation called 'translation', and a column called 'new_word' specifying which of the new words you've included in that sentence.
  Remember: you must include exactly _one_ of the 'new words' in each sentence, and the rest of the words must all already be present in the 'learned words', except for the exceptions I mentioned above.
  The output MUST be a .csv file with columns exactly as specified above.
  Do NOT say anything else, just output the raw .csv file and say nothing else. Do not wrap in ```, just output the raw .csv text.

# Defaults
grammar_instruction: ""
